name: CI/CD - Test HTML + Deploy Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-html:
    name: Vérification HTML
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification syntaxe HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .

  deploy-pages:
    name: Déployer sur GitHub Pages
    needs: test-html
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configurer Pages
        uses: actions/configure-pages@v5

      - name: Préparer l’artefact (site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Déployer
        id: deployment
        uses: actions/deploy-pages@v4
